env:
  browser: true
extends:
  - react-app
  - airbnb
  - prettier
plugins:
  - prettier
rules:
  valid-jsdoc: warn
  prettier/prettier: warn
  class-methods-use-this: 0
  react/jsx-filename-extension: 0
  react/jsx-one-expression-per-line: 0
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
  react/jsx-indent: 0

overrides:
  - files:
      - src/**/*.test.js
    env:
      jest: true
root: true
