parser: babel-eslint
env:
  browser: true
extends:
  - airbnb
  - prettier
plugins:
  - prettier
  - react-hooks
rules:
  valid-jsdoc: warn
  prettier/prettier: warn
  class-methods-use-this: 0
  react/jsx-filename-extension: 0
  react/jsx-one-expression-per-line: 0
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
root: true
