version: '3.8'

services:
  typing:
    image: "control-acc/typing-exp"
    environment: 
      MODERATOR_PASSWORD: "cheval"
      SUGGESTION_SERVER: "ws://localhost:8080"
    restart: on-failure
    ports:
      - target: 80
        published: 5000
    container_name: typing-exp
  words:
    image: "control-acc/words"
    restart: on-failure
    ports:
      - target: 80
        published: 8080
    container_name: words-suggestions