version: "3.8"

services:
  typing:
    build: .
    image: "suggestion-experiment/experiment"
    environment:
      MODERATOR_PASSWORD: "waterlooHCI"
      SUGGESTION_SERVER: "ws://localhost:8080"
    restart: on-failure
    ports:
      - target: 80
        published: 8000
    container_name: typing-exp

  words:
    build: suggestionServer
    image: "suggestion-experiment/words-api"
    restart: on-failure
    ports:
      - target: 80
        published: 8080
    container_name: words-suggestions