FROM node:13.12.0-slim AS build
WORKDIR /app/client
COPY ./client .
RUN npm install --production
RUN GENERATE_SOURCEMAP=false npx react-scripts build

# Use multi-stage build, to get rid of the client's dependencies once it has
# been built. 
FROM node:13.12.0-slim
WORKDIR /app/server
COPY ./control-server .
COPY --from=0 /app/client/build /app/client
COPY --from=0 /app/client/scripts/endpoints-from-env.js /app/
EXPOSE 80
RUN npm install --production
ENV STATIC_NOT_FOUND_FILE index.html
ENV SERVER_PORT 80
ENV STATIC_FILES /app/client
CMD node /app/endpoints-from-env > /app/client/endpoints.json \
  && node /app/server/index.js