version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16
    steps:
      - checkout
      - run:
          name: Install deps
          command: npm ci
      - run:
          name: Run app tests
          command: npm run test
      - run:
          name: Run script tests
          command: npm run test-scripts
